---
title: "ADNI_demo_diag_apoe"
author: "Xinyu Guo"
date: "6/24/2021"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(skimr)
library(vistime)
library(kableExtra)
library(ggplot2)
library(plotly)
library(ggplotify)
library(gridExtra)
```

# Load reference data
```{r}
pts <- read.csv("data_patients.csv")[, -1] %>% 
  select(-c("USERDATE", "USERDATE2", "COLPROT", "ORIGPROT", "EXAMDATE_bl", "EXAMDATE"))
```

# DIAG
```{r}
adni_diag <- read.csv("/Users/xinyuguo/OneDrive - Johns Hopkins/AD Biomarker/AD_Tools/ADTool/ADNI_data/Diag/DXSUM_PDXCONV_ADNIALL.csv") %>% 
  mutate(VISCODE = VISCODE2) %>% 
  select(-c(ID, PTID, SITEID, VISCODE2, USERDATE, 
            USERDATE2, update_stamp))
```

# DEMO
```{r}
adni_demo <- read.csv("/Users/xinyuguo/OneDrive - Johns Hopkins/AD Biomarker/AD_Tools/ADTool/ADNI_data/DEMO/PTDEMOG.csv") %>% 
  mutate(VISCODE = VISCODE2) %>% 
  select(-c(ID, SITEID, VISCODE2, USERDATE, 
            USERDATE2, update_stamp))
```

# APOE
```{r}
adni_apoe <- read.csv("/Users/xinyuguo/OneDrive - Johns Hopkins/AD Biomarker/AD_Tools/ADTool/ADNI_data/APOE/APOERES.csv") %>% 
  select(Phase, RID, VISCODE, APGEN1, APGEN2)
```

# Merged all three
```{r}
merged_data <- pts %>% 
  left_join(adni_demo, by = c("Phase", "RID", "VISCODE")) %>% 
  left_join(adni_diag, by = c("Phase", "RID", "VISCODE")) %>% 
  left_join(adni_apoe, by = c("Phase", "RID", "VISCODE"))
```

# Followup time plots
```{r}
followup_time <- pts %>% 
  group_by(RID) %>% 
  mutate(Followup_time = as.Date(EXAMDATE) - as.Date(EXAMDATE_bl)) %>% 
  arrange(RID, Followup_time, by_group = T) %>% 
  filter(!is.na(Followup_time)) %>% 
  filter(row_number() == n()) %>% 
  mutate(Followup_time = as.numeric(Followup_time) / 365)
hist(followup_time$Followup_time, breaks = 30)
```

```{r}
DXSUM_PDXCONV_ADNIALL <- read.csv("/Users/xinyuguo/OneDrive - Johns Hopkins/AD Biomarker/AD_Tools/ADTool/ADNI_data/Diag/DXSUM_PDXCONV_ADNIALL.csv")
PTDEMOG <- read.csv("/Users/xinyuguo/OneDrive - Johns Hopkins/AD Biomarker/AD_Tools/ADTool/ADNI_data/DEMO/PTDEMOG.csv")
APOERES <- read.csv("/Users/xinyuguo/OneDrive - Johns Hopkins/AD Biomarker/AD_Tools/ADTool/ADNI_data/APOE/APOERES.csv")

var_names <- names(DXSUM_PDXCONV_ADNIALL)
n <- length(var_names)
vars_diag <- data.frame(Source      = rep("ADNI", n), 
                        Type        = rep("DIAG", n), 
                        File        = rep("DXSUM_PDXCONV_ADNIALL", n), 
                        Vatiables   = var_names, 
                        Inter_name  = rep(NA, n), 
                        Description = rep(NA, n))

var_names <- names(PTDEMOG)
n <- length(var_names)
vars_demo <- data.frame(Source      = rep("ADNI", n), 
                        Type        = rep("DEMO", n), 
                        File        = rep("PTDEMOG", n), 
                        Vatiables   = var_names, 
                        Inter_name  = rep(NA, n), 
                        Description = rep(NA, n))

var_names <- names(APOERES)
n <- length(var_names)
vars_apoe <- data.frame(Source      = rep("ADNI", n), 
                        Type        = rep("APOE", n), 
                        File        = rep("APOERES", n), 
                        Vatiables   = var_names, 
                        Inter_name  = rep(NA, n), 
                        Description = rep(NA, n))

```










